# FROM golang:1.9 as build

# RUN go-wrapper download github.com/fogleman/primitive
# RUN go-wrapper install github.com/fogleman/primitive

FROM node:8-alpine

ARG PACKAGE_PATH=
ARG WORKING_DIR=/src

WORKDIR $WORKING_DIR

COPY $PACKAGE_PATH/package.json $WORKING_DIR/package.json
COPY $PACKAGE_PATH/package-lock.json $WORKING_DIR/package-lock.json
RUN npm install -g -s --no-progress yarn && \
    yarn 

# COPY . /src
# COPY --from=build /go/bin /bin

VOLUME $WORKING_DIR/node_modules
